### ISSUE TITLE
create Site table

### ISSUE THREAD

**Issue by uptownhr** [uptownhr/comments#13]
id: int primary,
domain: varchar 128
created: datetime "current_timestamp"

**Comment by PeterXay** [comment]
![screen shot 2015-05-27 at 10 41 02 am](https://cloud.githubusercontent.com/assets/12172279/7843206/eef3d46a-045c-11e5-95cf-998dd8941644.png)

I used Timestamp instead of datetime because it said Timestamp has by default current_timestamp feature

**Comment by PeterXay** [comment]
CREATE TABLE Site(
  id int,
  domain varchar(128),
  created datetime default current_timestamp, 
  PRIMARY KEY (id)
  )
